ar-io/ar-io-node

- docker-compose.yaml
Depends on https://github.com/ar-io/arns-resolver/pull/4
> fix(arns): update env var for arns resolver in docker-compose

- src/database/sql/bundles/import.sql
- src/events.ts
- src/routes/ar-io.ts
- src/system.ts
- test/end-to-end/indexing.test.ts
`queue-bundle` endpoint can be used to unbundle bundles that are not in the chain yet.
> feat(queue-bundle): add queue-bundle endpoint

- docker-compose.yaml
after user reports of not so logical issues and bugs, we are better off not using this feature.
> revert(docker-compose): prefer the previous anonymous-volumes

- docker-compose.yaml
depends on next upload service public image
> feat(queue data item): enable bundle sidecar optical post to local queue data item admin endpoint PE-6107

- package.json
- src/config.ts
- src/data/ar-io-data-source.ts
- src/system.ts
- yarn.lock
The SDK supports a new implementation of the same interfaces using the AO/IO contract.
> feat(io): use ao/io contract for fetching peer data sources

- src/arweave/composite-client.ts
- src/data/ar-io-data-source.test.ts
- src/data/ar-io-data-source.ts
- src/data/gateway-data-source.test.ts
- src/data/gateway-data-source.ts
- src/data/read-through-data-cache.test.ts
- src/data/read-through-data-cache.ts
- src/data/s3-data-source.ts
- src/data/sequential-data-source.ts
- src/data/test-utils.ts
- src/data/tx-chunks-data-source.test.ts
- src/data/tx-chunks-data-source.ts
- src/metrics.ts
Added getDataErrorsTotal, getDataStreamErrorsTotal and getDataStreamSuccesssTotal metrics for ContiguousDataSources.
> feat(data-sources): add getData metrics

- docker-compose.yaml
- package.json
- src/config.ts
- yarn.lock
We'll update the image tags from these two PRs before merging:
- resolver: https://github.com/ar-io/arns-resolver/pull/9
- observer: https://github.com/ar-io/ar-io-observer/pull/44
> feat(io): prep env vars and docker compose images for release 13

- src/constants.ts
- src/middleware/arns.ts
- src/resolution/memory-cache-arns-resolver.ts
- src/resolution/standalone-arns-resolver.ts
- src/resolution/trusted-gateway-arns-resolver.ts
- src/types.d.ts
- test/end-to-end/arns.test.ts
Related but non-blocking: https://github.com/ar-io/arns-resolver/pull/10
> feat(arns): add x-arns-processs-id in name resolution headers

- src/config.ts
- src/lib/env.ts
Replaces the current logic with a function that we can use again if necessary
> chore(env): create env function to generate random variable

- README.md
- docs/linux-setup.md
- docs/windows-setup.md
> Fix: correction typo

- package.json
- src/data/ar-io-data-source.test.ts
- src/data/ar-io-data-source.ts
- yarn.lock
The new changes use paginated requests for fetching larger items from state, include gateways.
> feat(sdk): bump @ar.io/sdk to use paginated requests for gateways

- src/filters.test.ts
- src/filters.ts
- src/types.d.ts
- test/end-to-end/indexing.test.ts
> feat(filters): add isNestedBundle filter

- src/config.ts
- src/resolution/on-demand-arns-resolver.ts
This should help avoid slamming AO when there are intermittent issues
> feat(arns): add circuit breaker for calling the IO network process

- src/app.ts
- src/constants.ts
- src/middleware/arns.ts
- src/routes/arns.ts
Useful for debugging HEAD requests to `*.<gateway-host>`
> chore(arns): add `X-ArNS-Resolved-At` header to resolution requests

- docs/envs.md
- src/config.ts
- src/routes/arweave.ts
* document new env-var `CHUNK_POST_MIN_SUCCESS_COUNT`
* make the minimum chunk post success count configurable
> feat(arweave): make chunk post count configureable

- docker-compose.yaml
sometimes docker does not restart when it fails
> Replace on-failure with unless-stopped docker-compose.yaml

- monitoring/grafana/dashboards/default.json
Will add a few other relevant dashboards with some of the latest metrics available.
> chore(grafana): fix unit for response time dashboard

- src/arweave/composite-client.ts
- src/config.ts
- src/metrics.ts
* add method 'peerGetChunk'
* attempt to fetch chunk from a random peer before trustedPeers
* new prometheus metrics 'request_chunk_total' and 'get_chunk_total'
* add env-var 'ARWEAVE_NODE_IGNORE_URLS' to remove specific peers from
the arweave node peer list
> feat: Search Arweave network for chunks

- src/database/standalone-sqlite.ts
- src/system.ts
- src/workers/ans104-data-indexer.ts
- src/workers/ans104-unbundler.ts
- src/workers/data-content-attribute-importer.ts
- src/workers/data-importer.ts
- src/workers/data-item-indexer.ts
- src/workers/data-verification.ts
- src/workers/transaction-fetcher.ts
- src/workers/transaction-importer.ts
- src/workers/transaction-offset-importer.ts
- src/workers/webhook-emitter.test.ts
- src/workers/webhook-emitter.ts
* remove all queue.drained calls in stop methods
* better error handling around pool/worker stops in db.stop
> fix: shutdown problems with db.stop when exit signal is received

- src/lib/data-root-streaming.test.ts
- src/lib/data-root-streaming.ts
- src/lib/data-root.ts
* added new function computeDataRootFromReadable
* added new unit tests for data-root-streaming
* apply the new function in data-root.ts
> feat(data-root): use data root compute from readable file stream

- .github/workflows/archive-codebase-to-arweave.yml
- .github/workflows/build-clickhouse-auto-import.yml
- .github/workflows/build-core-image.yml
- .github/workflows/build-core.yml
- .github/workflows/build-envoy.yml
- .github/workflows/build-litestream.yml
- .github/workflows/deploy-core-image.yml
- .github/workflows/docs.yml
- .github/workflows/test-core.yml
Note this part
> workflows: ['build-core']
That needs to match exactly the name of the workflow it depends on
> feat(ci): add deploy-core-image workflow for cd to ar-io.dev

- src/lib/string.ts
- src/routes/ar-io.ts
- src/routes/graphql/resolvers.ts
No tests were added as we currently doesn't have clickhouse tests
> fix(graphql): correctly handle empty cursor for clickhouse

- docker-compose.yaml
- src/filters.test.ts
- src/filters.ts
- src/log.ts
- src/system.ts
- src/types.d.ts
* add createObjectFilter for generic any object type filtering
* apply generic object filter to winston formatter
* introduce new env-var LOG_FILTER
> feat(logs): support for filtering winston logs

- src/arweave/composite-client.ts
- src/config.ts
- Moved config references into constructor.
- Added a circuit breaker for peer chunk posting.
- Removed unused preferred peers instance var (weights replace this).
> feat(chunks): add Arweave peer chunk POST circuit breaker

- src/routes/data/handlers.ts
`getData` implementations support returning data for regions (offset + size). This adjusts the data handler HTTP range request support to use the `getData` region functionality rather than streaming all the data for the ID to extract the ranges.
Note: for data handlers that do not have efficient region implementations (e.g. the chunk sources) this will be less efficient, but range requests that use those sources are uncommon and they can be optimized in the future.
> pref(data): pass ranges through to getData PE-8103

- src/database/composite-clickhouse.ts
- clean up leftover debug call in `CompositeClickHouse`
- `yarn lint:check`
- `yarn test` *(fails: 5 failing tests)*
> Remove stray console.log

- src/routes/data/handlers.test.ts
- src/routes/data/handlers.ts
For GET requests we only return digest and etag headers when data is cached locally since we don't want to accidentally stream data from the network that doesn't match the headers. For HEAD requests this is not a concern since no actual data is returned.
- Add If-None-Match support for both HEAD and GET requests
- Fix ETag format to use proper quoted strings
- Extend digest/ETag headers to HEAD requests for previously
> feat(routes data): add digest and hash headers for data HEAD requests

- src/routes/data/handlers.test.ts
- src/routes/data/handlers.ts
Previously, the Content-Length header was not being set for range requests (both single and multipart) in `src/routes/data/handlers.ts`.
This change ensures that:
- For single range requests, Content-Length is set to the length of the requested range.
- For multipart/byteranges requests, Content-Length is calculated by summing the lengths of all boundaries, part-specific headers, and the data for each part, and then set accordingly.
Unit tests in `src/routes/data/handlers.test.ts` have been added and updated to verify these changes, including assertions for Content-Length and Content-Range headers in various single and multipart range request scenarios (GET and HEAD), as well as for unsatisfiable ranges.
> Fix: Set Content-Length correctly for range requests
