ar-io/ar-io-node

- src/arweave/composite-client.ts
- src/database/standalone-sqlite.test.ts
- src/database/standalone-sqlite.ts
- src/metrics.ts
- src/system.ts
- src/workers/block-importer.test.ts
- src/workers/block-importer.ts
Consolidates metrics into `metrics.ts` and removes passing `prom-client.Registry` to various classes.
> refactor(metrics): consolidate metric definitions into metrics.ts

- docs/linux-setup.md
- docs/windows-setup.md
Added system requirements, updated yarn install instructions to work on ubuntu v22, separated required and recommended package installations on linux, minor wording/formatting updates.
> docs: Updates to getting-started guides

- src/app.ts
- src/config.ts
- src/middleware/arns.ts
- src/middleware/sandbox.ts
The sandbox and ArNS middleware didn't work when the node was hosted on a subdomain.
This PR adds subdomain support to both middlewares, so the node doesn't require a dedicated apex domain for hosting.
> Add subdomain support

- src/app.ts
- src/middleware/arns.ts
- src/routes/ar-io.ts
- src/routes/arns.ts
- src/routes/data/handlers.ts
- src/routes/data/index.ts
- src/routes/openapi.ts
As routes have five clear categories, splitting them into separate files to group them by category makes locating them in the file system easier. Related to issue #31
> refactor(routes): Move routes into a separate file

- docker-compose.yaml
- package.json
- src/config.ts
- src/lib/kvstore.ts
- src/store/fs-kv-store.ts
- src/store/kv-block-store.ts
- src/store/kv-transaction-store.ts
- src/store/lmdb-kv-store.test.ts
- src/store/lmdb-kv-store.ts
- src/system.ts
- src/types.d.ts
- yarn.lock
Introduces new interface `KvBufferStore` which allows various implementations of key/buffer stores for header cache data. Initially implemented with `lmdb` but intended to be extend to also include `redis` in the near future.
> feat(lmdb): introduce `KvBufferStore` and lmdb/fs based implementations for header cache 

- docker-compose.yaml
- package.json
- src/config.ts
- src/lib/kvstore.ts
- src/metrics.ts
- src/store/redis-kv-store.ts
- src/system.ts
- yarn.lock
This implementation is farily straightforward. We will add a `redis` container to the `docker-compose` and set is as the default `KvBufferStore` for header and transaction cache data once we validate it works as expected.
> feat(redis): add redis implementation of `KvBufferStore`

- src/app.ts
- src/config.ts
- src/system.ts
- src/workers/fs-cleanup-worker.ts
Now that we are using Redis as our default header cache, we would like to cleanup old headers on the filesystem. To accomplish that, this PR adds a generic filesystem cleanup worker and configures an instance of it to cleanup the files in data/headers.
> PE-5037: FS cleanup worker

- migrations/2024.01.17T21.54.57.core.add-stable-transaction-offsets.sql
- migrations/down/2024.01.17T21.54.57.core.add-stable-transaction-offsets.sql
- src/app.ts
- src/database/sql/core/async-import.sql
- src/database/standalone-sqlite.ts
- src/system.ts
- src/types.d.ts
- src/workers/transaction-fetcher.ts
- src/workers/transaction-offset-importer.ts
- src/workers/transaction-offset-repair-worker.ts
- test/bundles-schema.sql
- test/core-schema.sql
This change adds an 'offset' column to the stable_transactions table and a worker process that queries for missing offsets in the DB and fetches them from Arweave nodes. Queries for missing offsets are made efficient through the use of a partial index on the 'offset' where 'format' is 2 and 'data_size' is greater than 0 since those are the only transactions that should have offsets. For simplicity we currently only index offsets for stable transactions given they represent the bulk of the data.
The offset index can be used in the future for serving chunks requested by absolute offset directly from contiguous data sources.
> feat(chain sqlite): index stable transaction data offsets PE-2482

- envoy/envoy.template.yaml
These changes let Envoy listen on all IPv6 addresses (i.e., "::") in addition to IPv4 addresses (i.e., "0.0.0.0"). Related to issue #76.
> Adding backwards compatible IPv6 support

- package.json
- src/store/lmdb-kv-store.ts
- yarn.lock
This buffer check is no longer needed after the fix was pushed to lmdb@v2.9.x
> fix(lmdb): bump lmdb version and remove buffer check

- .github/workflows/archive-codebase-to-arweave.yml
This PR Adds Github action workflow that uses [Protocol.Land](https://protocol.land) and its [tools](https://github.com/labscommunity/protocol-land-sync) to archive entire codebase on Arweave.
This workflow depends on `WALLET` (arweave wallet JWK) added to the repo secrets with sufficient funds to be able to upload archive on Arweave.
Currently workflow has to be triggered manually, but I'm happy to adjust that in the action if this needs to run based on a condition like merge to master.
> Add action to archive codebase on Arweave

- src/database/standalone-sqlite.ts
The names were incorrectly prefixed with the class name. This in turn caused reading from the cache to fail. This change fixes the prefix to resolve the caching issue.
> fix(data sqlite): fix method names in circuit break queueRead calls

- src/routes/data/handlers.test.ts
- src/routes/data/handlers.ts
When doing a HEAD request for `/tx-id` or `/raw/tx-id` endpoints the server will not process the data stream while responding. It will use the cached data information to set the headers and if no cache is found it will process the data from the referenced gateway and cache it.
> feat(data handlers): stop processing data stream for HEAD requests

- docs/openapi.yaml
- envoy/envoy.template.yaml
- src/routes/data/index.ts
ar.io gateways now support (GET and POST) calls to /local/farcaster/frame/<txId>
> feat(farcaster): add initial frame support

- docker-compose.yaml
- src/config.ts
- src/init/resolvers.ts
- src/resolution/standalone-arns-resolver.ts
- src/system.ts
Implements the `NameResolver` interface in the `StandaloneArNSResolver` class whucg  arns name data from locally hosted arns-resolver service. Continues to use gateway by default - but allows for configurability via two new environment variables to select which resolver service to use. The changes do not remove any env vars or change default behavior. Additionally, the APIs on the arns-resolver service follow existing patterns and can be added to the envoy template once testing validates the expected behavior.
> feat(PE-5859): support standalone arns-resolver

- scripts/codedeploy/before-install
- Calling docker-compose before deleting `docker-compose.yaml`
- Checking that DB files exist before attempting a copy
> Fix CodeDeploy BeforeInstall script

- src/database/standalone-sqlite.test.ts
- src/database/standalone-sqlite.ts
- src/types.d.ts
- Correct NULL sort order - the SQLite default is different from Postgres (SQLite uses NULLs first for ASC).
- Include 'indexed_at' and 'id' in the cursor. These are needed in order to page through pending transactions and data items (id is needed when created_at is ambiguous).
> fix(graphql): correct pending sort order and pagination PE-6097

- docker-compose.yaml
on MacOS systems, port 5000 is always in use by `AirPlay Receiver` and prevents the default configuration from working when running docker compose on darwin systems.
> fix(docker+darwin) change default observer port from osx reserved 5000

- src/store/fs-kv-store.ts
- src/store/lmdb-kv-store.ts
This is not breaking, but if we're to upgrade our tsconfig to use `NodeNext` these will error.
> chore(imports): use proper import convention in kv stores for types.js

- .gitignore
- docker-compose.yaml
This PR updates the docker compose to take advantage of persisted localstack state between docker compose. This way, the sidecar bundler pipeline can continue to access data items and bundles that may be in flight during restarts
> feat(localstack): use persisted state by default PE-6154

- src/database/sql/bundles/import.sql
- src/database/standalone-sqlite.ts
- src/routes/ar-io.ts
- src/system.ts
- src/types.d.ts
- test/end-to-end/indexing.test.ts
This PR adds a queue data item admin endpoint 
would still like to add E2E tests and tests around upsert
manual test example:
```sh
curl -X POST http://localhost:3000/ar-io/admin/queue-data-item \
-H "Authorization: Bearer secret" \
-H "Content-Type: application/json" \
-d '[{
"id": "cTbz16hHhGW4HF-uMJ5u8RoCg9atYmyMFWGd-kzhF_Q",
"owner": "owner",
"owner_address": "owner_address",
"signature": "signature",
"target": "target",
"anchor": "anchor",
"content_type": "content_type",
"data_size": 1234,
"tags": [
{ "name": "QnVuZGxlLUZvcm1hdA", "value": "YmluYXJ5" },
{ "name": "QnVuZGxlLVZlcnNpb24", "value": "Mi4wLjA" }
]
}]'
```
> feat(queue data item): init admin route for accepting data item headers before they are bundled PE-6220

- migrations/2024.06.06T16.04.48.bundles.import-attempt-count-last-queued-at-indexes.sql
- migrations/down/2024.06.06T16.04.48.bundles.import-attempt-count-last-queued-at-indexes.sql
- src/database/sql/bundles/repair.sql
- src/database/standalone-sqlite.ts
- test/bundles-schema.sql
Changed order for selectFailedBundleIds query. Now order combine `import_attempt_count` and `last_queued_at`.
Added an indexed for `import_attempt_count` and `last_queued_at`.
> fix(sqlite): selectFailedBundleIds order

- src/data/ar-io-data-source.ts
- src/data/s3-data-source.ts
- src/store/redis-kv-store.ts
- src/system.ts
- src/workers/ans104-data-indexer.ts
Following a general policy to minimize the logs of error messages to only relevant information. This does not address all error messages, but ones in critical paths.
> chore(logs): updating error messages to only log the message and stack

- .eslintrc
- migrations/2024.06.13T13.52.01.bundles.nullable-parent-and-root.sql
- migrations/down/2024.06.13T13.52.01.bundles.nullable-parent-and-root.sql
- src/database/standalone-sqlite.ts
- src/routes/ar-io.ts
- src/system.ts
- src/types.d.ts
- src/workers/ans104-data-indexer.ts
- src/workers/ans104-unbundler.ts
- test/bundles-schema.sql
- test/end-to-end/indexing.test.ts
For expedience, the initial optimistic indexing code used placeholder values for root TX ID and parent. While this mostly works, it's confusing and produces inaccurate GQL results without extra post processing (optimistic data item parents are wrong). This change modifies the DB to allow null parent, root transaction ids, and offsets. It also adjusts types to allow for this and introduces extra conditionals to ensure that bundle imports and data indexing for optimistically indexed data items are not attempted. This prevents errant optimistic data items from making their way into the stable indexes.
> refactor(sqlite): use null parent and root TX ID for optimistic data items PE-6284

- src/data/ar-io-data-source.test.ts
I did not update these tests when moving to IO/AO contract in peer-data implementation.
> fix(test): fix IO in e2e data sharing tests

- docker-compose.yaml
- src/data/ar-io-data-source.test.ts
- src/data/gateway-data-source.test.ts
- src/data/read-through-data-cache.test.ts
- src/data/tx-chunks-data-source.test.ts
- src/routes/graphql/resolvers.test.ts
- test/end-to-end/bundler-sidecar.test.ts
This PR adds an E2E test that brings up the docker compose bundler profile, posts data, and expects the data to be accessible via the core ar.io gateway and the headers to have been optimistically indexed
> test(bundler sidecar): init data post e2e test PE-6266

- docker-compose.yaml
Resolver now supports separate env vars for the cache TTL and evaluation interval.
Ticket: [PE-6355](https://ardrive.atlassian.net/browse/PE-6355)
Related: https://github.com/ar-io/arns-resolver/commit/3b7ee23d111d19f58601df0d79bfea83689e3a34
[PE-6355]: https://ardrive.atlassian.net/browse/PE-6355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(arns): bump resolver image

- scripts/codedeploy/app-start
I'm not able to test if the legacy `docker-compose` cli command supports `--profile` flag. I hope it does.
EDIT: it was introduced in docker-compose v2 so this should work just fine.
> feat(codedeploy): add litestream profile flag to app-start

- docs/linux-setup.md
- docs/windows-setup.md
Recent security updates prevent resolving content on a gateway using localhost. As such, instructions to test a gateway at startup using localhost have been removed.
> docs: removed instructions to test gateway on localhost

- docs/openapi.yaml
Some inconsistencies and copy/pasta causing invalid openapi doc. We may want to consider adding a pre-commit hook that validates this spec is never corrupt.
> chore(docs): cleanup openapi docs

- src/config.ts
- src/init/resolvers.ts
- src/resolution/composite-arns-resolver.ts
- src/resolution/memory-cache-arns-resolver.ts
- src/resolution/on-demand-arns-resolver.ts
- src/resolution/standalone-arns-resolver.ts
- src/system.ts
- test/end-to-end/data.test.ts
Also introduces a `CompositeArNSResolver` that attempts to resolve a name against each provided resolver in order. By default, if `on-demand` is set and other URLs are provided, it will attempt to fallback to those. If `resolver` or `trustedGatewayUrl` is set, it will fallback to AO. Welcome any feedback on these "defaults" fallbacks.
This is experimental way to allow name resolution directly through AO infrastructure rather than relying on the resolver or other gateways. We may want to fallback to those if this experiences a high rate of errors, potentially using a circuit breaker or some sort. For now, it is an opt-in feature that is useful when testing arns workflows.
Logs: OnDemandArNSResolver
```bash
ar-io-node-core-1  | info: Resolved name …
```
> feat(arns): allow for on-demand name resolution, introduce composite arns resolver with fallbacks

- src/data/signature-fetcher.test.ts
- src/data/signature-fetcher.ts
- src/init/header-stores.ts
- src/routes/ar-io.ts
- src/store/kv-signature-store.ts
- src/system.ts
- src/types.d.ts
- Implement `KvSignatureStore` for caching signatures using with a 4-hour TTL (when using Redis).
- Modified `SignatureFetcher` to use the new signature store, checking for cached signatures before fetching from other sources.
- Implemented signature caching in the ar-io route for data item headers.
> feat(signature-store): add redis-backed signature store

- src/arweave/composite-client.ts
- src/metrics.ts
- src/system.ts
- src/workers/bundle-data-importer.ts
- src/workers/data-content-attribute-importer.ts
- src/workers/transaction-fetcher.ts
- src/workers/transaction-importer.ts
- src/workers/transaction-offset-importer.ts
- src/workers/webhook-emitter.ts
Add metrics for the depth of the following queues:
- Arweave trusted noderequest queue (composite client)
- Data content attribute importer
- Transaction fetcher
- Transaction importer
- Transaction offset importer
- Webhook emitter
- Data item indexer
- ANS104 data indexer
- ANS104 unbundler
- Bundle data importer
Example of the metrics:
```
queue_length{queue_name="arweaveClientRequests"} 0
queue_length{queue_name="txFetcher"} 0
queue_length{queue_name="txImporter"} 0
queue_length{queue_name="txOffsetImporter"} 0
queue_length{queue_name="dataContentAttributeImporter"} 0
queue_length{queue_name="dataItemIndexer"} 13028
queue_length{queue_name="ans104DataIndexer"} 12031
queue_length{queue_name="ans104Unbundler"} 1003
queue_length{queue_name="bundleDataImporter"} 0 …
```
> feat(metrics): Add queue depth metrics

- src/routes/arns.ts
- test/end-to-end/arns.test.ts
This is the same behavior in the middleware, but does not fetch the data. Useful for those that just want resolution info for a name.
> feat(PE-6738): introduce arns resolver GET endpoint

- src/app.ts
- src/config.ts
- src/init/resolvers.ts
By defaulting this in the service, there is no way to disable gateway arns resolution. Instead we will leave the default in the docker-compose and set to undefined if not provided to disable always falling back to arweave.net
> fix(arns): remove service default for TRUSTED_ARNS_GATEWAY_URL

- src/resolution/composite-arns-resolver.ts
- src/resolution/on-demand-arns-resolver.ts
- src/types.d.ts
Without this it's easy for non-existent names to DOS the CUs we're using to resolve names. This change caches non-existent name resolutions for 5 minutes in the in-memory/Redis cache.
> perf(arns): cache resolution for non-existent name

- src/database/sql/data/content-attributes.sql
The OR in the previous query was preventing effective index usage. This change modifies the query to use a UNION of lookup by ID and data root. That's a much simpler query for the optimizer to understand, and it uses indexes for both.
> perf(sqlite data): switch OR to a UNION in data attributes query PE-6806

- src/routes/ar-io.ts
- src/workers/parquet-exporter.ts
The new `/ar-io/admin/export-parquet/status` endpoint will return a json message with the following structure:
```
{
pending: boolean;
outputDir?: string;
startHeight?: number;
endHeight?: number;
maxFileRows?: number;
durationInSeconds?: number;
error?: string;
}
```
`pending` is always present and the other attributes are present when needed.
> feat(parquet-exporter): add status endpoint for parquet export

- package.json
- src/database/standalone-sqlite.ts
Prior to this commit, data items were flushed via the core DB writer. Under sufficiently heavy bunde import load this lead to contention with data item writes. This change adjusts the flushing logic to use the bundle DB writer. This avoids concurrent bundle DB write attempts and eliminates the contention.
> fix(sqlite): flush data items using bundle db writer PE-6872

- src/database/standalone-sqlite.ts
- src/metrics.ts
Example of metrics:
```
sqlite_in_flight_ops{worker="core",role="read"} 0
sqlite_in_flight_ops{worker="core",role="write"} 0
sqlite_in_flight_ops{worker="bundles",role="write"} 1
sqlite_in_flight_ops{worker="data",role="read"} 0
sqlite_in_flight_ops{worker="data",role="write"} 1
```
> feat(metrics): add database in-flight operations metrics

- README.md
- docker-compose.grafana.yaml
- monitoring/grafana/dashboards/default.json
- monitoring/grafana/provisioning/dashboards/dashboards.yaml
- monitoring/grafana/provisioning/datasources/datasources.yaml
- prometheus.yml
This PR adds a lightweight observability stack using `prometheus`, `node-exporter`, and `grafana`, and includes a default dashboard surfacing some relevant metrics. It runs independently of the core `ar-io-node` services and can be improved with additional prometheus stats available on all gateways. We might later use jsonnet for advanced dashboards aimed at larger-scale operators.
> chore(monitoring): introduce basic observability stack using grafana & prometheus

- docs/madr/002-arns-cache-timing.md
Adds an ADR that defines the set of parameters that control ArNS cache refresh behavior.
> docs(adrs): add draft ArNS cache behavior ADR

- src/database/standalone-sqlite.ts
This is causing and uncaught exception `Uncaught exception: Error in StandaloneSqlite worker","name":"DetailedError","stack":"RangeError: Missing named parameter \"created_at\"\n    at StandaloneSqliteDatabaseWorker.blockName (file:///app/dist/database/standalone-sqlite.js:1581:48)\n `
> fix(db): add created_at field when blocking name

- package.json
- src/data/ar-io-data-source.test.ts
- src/data/ar-io-data-source.ts
- src/init/resolvers.ts
- src/resolution/arns-names-cache.test.ts
- src/resolution/arns-names-cache.ts
- src/resolution/on-demand-arns-resolver.ts
- src/system.ts
- yarn.lock
The newest version of the SDK leverages newest handlers and updated types. It also includes the modifications to align with the ARIO token branding.
Related: https://github.com/ar-io/ar-io-observer/pull/54
> chore(deps): update ar-io-sdk to v3.1.0

- src/resolution/composite-arns-resolver.ts
- src/resolution/on-demand-arns-resolver.ts
- test/end-to-end/arns.test.ts
The arns name cache only contains base names. When an undername is requested, it fails to find the full undername in the cache and results in a 404. This modifies the behavior to parse out the base name from an undername, and check the arns name cache for that base name first. Then it checks the resolution cache for the full name data of the undername. Additional e2e tests have been added to ensure this behavior does not regress in future modifications to arns handling.
> fix(arns): fix undername resolution, add e2e tests

- docs/madr/002-arns-cache-timing.md
- package.json
- src/config.ts
- src/init/resolvers.ts
- src/resolution/arns-names-cache.test.ts
- src/resolution/arns-names-cache.ts
- src/resolution/composite-arns-resolver.ts
- src/store/kv-arns-base-name-store.ts
- src/store/kv-arns-name-resolution-store.ts
- src/store/kv-debounce-store.test.ts
- src/store/kv-debounce-store.ts
- src/system.ts
- yarn.lock
Adds debouncing to the arns name list on cache hit/misses based on newly exposed variables. These should help alleviate name resolution delays for new names, as the cache will be refreshed within 10 seconds on misses (by default). Additionally, operators can choose to set cache hit debounce interval separate from the cache TTL, allowing tighter control of how often to refresh the cache - but always preserving it for at least the TTL if it fails to request an updated list from the CU. Refer to the updated ADR for specifics on how these caching mechanisms are architected.
Update:
Introducing a new `Kv-Debounce-Store` which accepts any existing `KvStore` implementation and a `hydrateFn` that is called after the provided debounce intervals.
> fix(arns): introduce cache miss/hit debouncing for arns name cache

- src/metrics.ts
- src/resolution/arns-names-cache.ts
- src/resolution/composite-arns-resolver.ts
Example:
```
arns_name_cache_duration_ms{quantile="0.01"} 4614
arns_name_cache_duration_ms{quantile="0.05"} 4614
arns_name_cache_duration_ms{quantile="0.5"} 5371.5
arns_name_cache_duration_ms{quantile="0.9"} 6129
arns_name_cache_duration_ms{quantile="0.95"} 6129
arns_name_cache_duration_ms{quantile="0.99"} 6129
arns_name_cache_duration_ms{quantile="0.999"} 6129
arns_name_cache_duration_ms_sum 10743
arns_name_cache_duration_ms_count 2
arns_name_cache_hit_total 1
arns_name_cache_miss_total 1
```
> chore(metrics): add arns name cache hit/miss prometheus counters

- docs/linux-setup.md
Updated Linux setup guide for more involved method of installing latest docker version, and changed commands from `docker-compose` to the newer `docker compose`
> Docs: Update setup guides for `docker compose` over `docker-compose`

- test/end-to-end/data-sources.test.ts
- test/end-to-end/indexing.test.ts
Skipping these frequently failing tests for now. Will look to fix them in a separate commit.
These two tests are the main offenders - and on initial inspection it looks like mostly a timing issue.
> chore(test): disabling flaky e2e tests

- src/config.ts
- src/lib/data-root.ts
- src/workers/data-verification.ts
- test/end-to-end/data-sources.test.ts
- test/end-to-end/indexing.test.ts
We need to index the bundle transaction before we can attempting to verify its data root.
> chore(test): fix data verification test

- docs/envs.md
- src/arweave/composite-client.ts
- src/config.ts
- src/data/ar-io-data-source.test.ts
- src/data/ar-io-data-source.ts
- src/data/gateways-data-source.ts
- src/data/read-through-data-cache.ts
- src/data/s3-data-source.ts
- src/data/tx-chunks-data-source.ts
- src/lib/random-weighted-choices.ts
- src/metrics.ts
* adding 'peer' label to prometheus data retrival metrics
* add lib helper 'random-weighted-choices' for returning weighted random list
* add retry mechanism, retrying over random and unique gateway peers
> feat: weighted gateway peers for data retrievals

- src/config.ts
This aligns the default with the ADR, and likely the cause of some of the pain felt by operators.
> fix(config): default names cache TTL to one hour

- src/config.ts
- src/middleware/arns.ts
- src/resolution/arns-names-cache.ts
- src/resolution/composite-arns-resolver.ts
- src/resolution/on-demand-arns-resolver.ts
- src/resolution/trusted-gateway-arns-resolver.ts
- src/routes/arns.ts
- src/store/kv-debounce-store.test.ts
- src/store/kv-debounce-store.ts
- src/types.d.ts
- Don't make unnecessary requests to get base names.
- Don't unnecessarily wait on request to refresh the base name list.
- Ensure only one base name request in flight at once.
- Refresh ANTs in the background only when the cache is about to expire.
- Ensure only one ANT refresh at a time is in flight.
> ArNS ADR alignment and performance improvements

- src/database/sql/data/contiguous-data-ids.sql
- src/database/standalone-sqlite.test.ts
- src/database/standalone-sqlite.ts
- src/routes/data/handlers.test.ts
- src/types.d.ts
- src/workers/data-verification.ts
Change `getUnverifiedDataIds` to `getVerifiableDataIds`. It will now only select contiguous data ids associated with root transactions
> fix(db): getVerifiableDataIds

- src/arweave/composite-client.ts
Sometimes the refreshPeers stalls indefinitely. We should be sure that there's some timeout here in place that prevents that.
> fix(peers): set a timeout for refresh peers axios call

- src/database/standalone-sqlite.test.ts
- src/database/standalone-sqlite.ts
In SQLite we sort results using a placeholder value for data item IDs when data items are not available. In the ClickHouse adapter we instead sort results using a flag indicating whether or not the row is a data item (the order is the same with both approaches). Until this commit, GraphQL cursors in both implementations reflected this difference. This change adjusts the SQLite cursors to match the ClickHouse cursors so that we can more easily combine results in the future. This is accomplished by converting placeholder data item ID values to/from boolean data item indicators in the cursor.
> refactor(sqlite graphql): adjust cursors to align with ClickHouse adapter PE-6482

- src/config.ts
- src/filters.ts
- src/lib/ans-104.ts
- src/system.ts
With debug logs enabled, we can debug complicated bundle indexing filters and see the tree of user provided filters and if they are matching or not. This can simplify debugging process for users with multiple filters or complicated match criteria.
EDIT: Im adding default argument to a logger that isn't passed to make it simpler to make tests and experiment in the cli. But if we pass the logger right then we get the trees correctly.
> feat(filters): log the matching status of each filter

- src/routes/ar-io.ts
- src/workers/parquet-exporter.ts
Exported parquet file names are now aligned with what import parquet script expects.
Example:
```
blocks-0-185-rowCount:186.parquet
transactions-0-185-rowCount:331.parquet
```
> fix(parquet): fix export parquet names

- src/app.ts
Applying the default route middleware before ArNS breaks ArNS handling.
> fix(routes): apply default middleware after arns PE-7310

- package.json
- src/resolution/on-demand-arns-resolver.ts
- test/end-to-end/arns.test.ts
- yarn.lock
We will replace this URL with a local cu, but the setup requires a bit more work so these changes fix the current tests and use https://cu.ardrive.io by default
Isolated test results:
```bash
yarn run v1.22.22
$ node --import ./register.js --test test/**/arns.test.ts
▶ ArNS
▶ Subdomain resolution
▶ Base names
✔ Verifying "__unknown__.ar-io.localhost" returns 404 (2449.51303ms)
✔ Verifying "ardrive.ar-io.localhost" returns 200 (573.922816ms)
✔ Verifying "ardrive.ar-io.localhost" X-ArNS-Resolved-ID header (22.543828ms)
✔ Verifying "ardrive.ar-io.localhost" X-ArNS-TTL-Seconds header (13.362679ms)
✔ Verifying "ardrive.ar-io.localhost" X-ArNS-Process-ID header (15.827781ms)
✔ Verifying "ardrive.ar-io.localhost/{txid}" is redirected (7.624408ms)
✔ Verifying "ardrive.ar-io.localhost" …
```
> chore(arns): bump ar-io-sdk and update tests to use custom CU url

- envoy/envoy.template.yaml
- src/routes/default.ts
- Correct copy pasta that failed to add redirect handling and host rewriting on pass-through Arweave Envoy routes.
- Pass `/info` through to Arweave nodes in the Envoy config.
- Pass `/current_block` through to Arweave nodes in the Envoy config.
- Pass `/graphql` on to the next in the wildcard route since Apollo always attaches its routes last.
> fix(routes envoy): Envoy /info and host rewriting + /graphql for apex

- monitoring/grafana/dashboards/default.json
The dashboard was defined with static datasource , so it's you need to modify it manually if ur grafana was installed in different server. I've add new panel "Datasource" for user select their datasource, also make the other panel integrated with the datasource panel.
> feat: update grafana dashboard json, make dynamic datasource

- src/arweave/composite-client.ts
- Replace `weightedChunkPeers` references with a single `weightedPeers` array to standardize weighted peer handling.
- Rename `selectChunkPeers()` to `selectPeers()` for broader usability.
- Update `peerGetTx()` to:
- Attempt fetching from multiple weighted peers before failing over to the trusted node.
- Adjust peer weights on success or failure using `handlePeerSuccess()` and `handlePeerFailure()`.
- Switch chunk-fetch logic calls from `selectChunkPeers` to `selectPeers`.
- Ensure peer weighting logic applies consistently for both chunk and transaction fetching.
- Increase the default peer request timeout in `peerGetTx()` from 500ms to 1000ms.
> feat: add robust TX header fetching with multiple weighted peers

- src/arweave/composite-client.ts
- src/config.ts
- Introduced peer chunk broadcasting after secondary posting.
- Added support for weighted peer selection via `weightedPostChunkPeers`.
- Controlled via `ARWEAVE_PEER_CHUNK_POST_MIN_SUCCESS_COUNT_STRING` and `ARWEAVE_PEER_CHUNK_POST_CONCURRENCY_LIMIT_STRING`.
- Refactored `weightedChunkPeers` into `weightedGetChunkPeers` and `weightedPostChunkPeers` for clarity.
- Updated chunk fetching logic to use new `weightedGetChunkPeers`.
- Only HTTP 200 responses count as successful.
> feat(arweave): add chunk broadcasting to weighted peer network [PE-7945]

- package.json
- src/config.ts
- src/data/legacy-psql-chunk-metadata-cache.ts
- src/data/s3-chunk-source.ts
- src/store/fs-chunk-data-store.ts
- src/system.ts
- src/types.d.ts
- yarn.lock
- Add `postgres` as a new dependency.
- Introduce configuration options for PostgreSQL in `config.ts`, including support for secure password files and SSL.
- Establish a conditional `postgres` client instance in `system.ts` that only connects when configuration is provided.
- Define a new `LegacyChunkMetadata` type to match the legacy chunk structure in Postgres.
- Prepare system to support a new Postgres-based implementation of `ChunkMetadataByAnySource` for serving chunk metadata via the standard `/chunk/<offset>` interface.
> feat: add Postgres support for legacy chunk metadata (PE-7904)

- src/routes/default.ts
When there was a subdomain in ARNS_ROOT_HOST, the existing code failed to include it when adding the apex ArNS name. This change extracts any subdomains from the ARNS_ROOT_HOST and includes them when overriding the request subdomain.
> fix(routes): fix subdomain with apex arns name PE-7947

- envoy/envoy.template.yaml
This routes /height to arweave nodes. The openapi docs alreay have the endpoint documented, but it did not route as expected.
Existing docs: https://github.com/ar-io/ar-io-node/blob/develop/docs/openapi.yaml#L919-L931
```bash
❯ curl localhost:3000/height
1659148
```
> fix(envoy): add /height to envoy routing

- src/app.ts
Browsers do not allow accessing of headers if they are not set in the cors configuration.
> chore(app): expose all ario headers in cors configuration

- src/config.ts
- src/data/composite-chunk-source.ts
- src/data/read-through-chunk-metadata-cache.ts
- src/data/s3-chunk-source.ts
- src/routes/chunk/handlers.ts
- src/routes/chunk/index.ts
- src/system.ts
- src/types.d.ts
- Create CompositeChunkSource to unify chunk data and metadata retrieval
- Replace separate chunkDataSource and chunkMetaDataSource with unified chunkSource in route handlers
- Refactor handler to work with composite Chunk objects (data + metadata)
- Remove redundant metadata fetch logic from chunk handler
- Introduce new Chunk interface that extends ChunkMetadata and ChunkData with optional tx_path
- Update S3ChunkSource to support rawResponsePayload mode using aws-lite
- Ensure chunk body is a Buffer and validate S3 responses defensively
- Add support for AWS_SESSION_TOKEN in config and awsClient setup
- Restructure system.ts to initialize chunkSource conditionally based on config
- Clean up imports and parameter lists in affected modules
> feat: introduce CompositeChunkSource and refactor chunk handling (PE-8012)

- src/arweave/composite-client.ts
- src/data/ar-io-data-source.ts
- src/routes/ar-io.ts
- src/system.ts
- src/types.d.ts
- test/end-to-end/ar-io.test.ts
Includes gateways and nodes. We can add more to the gateways peer lists based on weights when useful.
> feat(api): add peer list endpoint

- src/app.ts
These are needed, specifically content-length, for wayfinder to verify data from the gateway.
> fix(headers): add content-* headers to CORS

- src/middleware/arns.ts
When APEX_ARNS_NAME is set, navigating to /api-docs/  works but /api-docs **does not**
> chore(docs): set regex for /api-docs to allow optional /

- test/end-to-end/data.test.ts
- ensure stream assertions run after resolution in tests
- `yarn lint:check` *(fails: package not present in lockfile)*
- `yarn test:e2e` *(fails: package not present in lockfile)*
> Fix streaming data tests

- src/lib/encoding.ts
- remove duplicate fallback clause in `parseManifestStream`
- `yarn test` *(fails: package not in lockfile)*
> Fix duplicate fallback logic in manifest parser

- src/workers/data-verification.ts
- fix typo in DataVerificationWorker log statement
- `node --import ./register.js --test src/workers/data-verification.test.ts` *(fails: cannot find package 'ts-node')*
> Fix typo in data verification log message

- src/middleware/arns.ts
- ensure `www` is in the excluded subdomain set
- test that the ArNS middleware skips resolution for the `www` subdomain
- `yarn test` *(fails: This package doesn't seem to be present in your lockfile)*
> Fix ArNS www exclusion

- docs/openapi.yaml
- src/routes/data/handlers.ts
- src/workers/fs-cleanup-worker.ts
- test/end-to-end/data.test.ts
- set caching headers before handling byte ranges
- document X-Cache and related headers for 206 responses
- test that range responses include cache header
- `npx eslint src test`
- `npm test` *(fails: fetch failed)*
> Fix cache headers on range requests

- src/middleware/arns.ts
- tidy comment about undername length in ArNS middleware
- `yarn test` *(fails: package missing in lockfile)*
> Fix undername comment

- package.json
- src/routes/ar-io.ts
- yarn.lock
- replace `express-prometheus-middleware` with `@matteodisabatino/express-prometheus-middleware`
- bump `prom-client` version
- drop custom `gc-stats` resolution
- `yarn lint:check` *(fails: Invalid option '--verbose')*
- `yarn test` *(fails: 5 failing tests)*
> Update prometheus middleware dependency

- src/database/sql/bundles/flush.sql
- ensure root_parent_offset is preserved when flushing new_data_items to stable_data_items
- `yarn test` *(fails: package missing from lockfile)*
> Fix root_parent_offset flush to stable_data_items

- tsconfig.prod.json
- update `tsconfig.prod.json` to exclude the `test` dir
- `yarn build` *(fails: package not present in lockfile)*
> Fix test dir exclusion

- src/constants.ts
- src/data/ar-io-data-source.test.ts
- src/data/ar-io-data-source.ts
- Added hash validation when fetching data from ar.io network peers
- Prevents accidental propagation of data that doesn't match local hashes
- Maintains backward compatibility with peers that don't support digest headers
- Added `X-AR-IO-Expected-Digest` header constant
- Updated `ArIODataSource` to send expected hash in request headers when available
- Added validation in `parseResponse()` to check peer's `X-AR-IO-Digest` against expected hash
- Added comprehensive unit tests for all hash validation scenarios
- Test successful data fetch when hashes match
- Test rejection when hashes don't match
- Test behavior when no expected hash is provided
- Test backward compatibility when peer doesn't provide digest header
> feat(data): add hash validation for peer data fetching PE-8238

- src/middleware/arns.ts
- src/resolution/arns-names-cache.test.ts
- src/routes/arns.ts
- src/store/kv-debounce-store.ts
Fixes PE-8415: Debug ID resolution during ArNS startup
- Avoid populating ArNS response headers with undefined values
- Wait for in-progress ArNS name-cache hydration before reporting cache misses
- Test immediate ArNS cache requests waiting for hydration
This PR addresses the issue where ArNS names were resolving to "undefined" (string) as an ID before ArNS caches were populated. The fix ensures that:
1. Response headers are not populated with undefined values
2. The system waits for cache hydration to complete before reporting cache misses
3. Proper handling of cache requests during the hydration phase
- `npm test` *(fails: should recover the correct owner from a signed transaction, should handle write permission errors gracefully)*
- …
> Avoid undefined ArNS headers and await cache hydration

- .env.hb.example
- docker-compose.hb.yaml
To use it, enable the following in the `.env`:
```bash
ARNS_RESOLVER_PRIORITY_ORDER=on-demand
AO_ANT_HYPERBEAM_URL=hyperbeam:10000
```
and run:
`docker compose up -d && docker compose -f docker-compose.hb.yaml up -d`
> chore(hb): add optional hypberbeam sidecar
